/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Agency;
import org.openapitools.client.model.AgencyHeader;
import org.openapitools.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgencygroupApi
 */
@Disabled
public class AgencygroupApiTest {

    private final AgencygroupApi api = new AgencygroupApi();

    /**
     * Get a Branch by ID
     *
     * Get a Branch by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBranchTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String agencyDid = null;
        String branchDid = null;
        String xIBMClientSecret = null;
        Agency response = api.getBranch(xIBMClientId, authorization, agencyDid, branchDid, xIBMClientSecret);
        // TODO: test validations
    }

    /**
     * Get a list of branches
     *
     * Get a list of branches
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listBranchesTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String agencyDid = null;
        String xIBMClientSecret = null;
        List<AgencyHeader> response = api.listBranches(xIBMClientId, authorization, agencyDid, xIBMClientSecret);
        // TODO: test validations
    }

}
