/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Agency;
import org.openapitools.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgencygroupworkflowApi
 */
@Disabled
public class AgencygroupworkflowApiTest {

    private final AgencygroupworkflowApi api = new AgencygroupworkflowApi();

    /**
     * Request for linking a branch agency
     *
     * Request for linking a branch agency
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void linkAgencyBranchTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String agencyDid = null;
        String branchDid = null;
        Object request = null;
        String xIBMClientSecret = null;
        Agency response = api.linkAgencyBranch(xIBMClientId, authorization, agencyDid, branchDid, request, xIBMClientSecret);
        // TODO: test validations
    }

    /**
     * Request for unlinking a branch agency
     *
     * Request for unlinking a branch agency
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unLinkAgencyBranchTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String agencyDid = null;
        String branchDid = null;
        Object request = null;
        String xIBMClientSecret = null;
        Agency response = api.unLinkAgencyBranch(xIBMClientId, authorization, agencyDid, branchDid, request, xIBMClientSecret);
        // TODO: test validations
    }

}
