/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AgencyeventsApi
 */
@Disabled
public class AgencyeventsApiTest {

    private final AgencyeventsApi api = new AgencyeventsApi();

    /**
     * Archive an agency in TARS
     *
     * Archive an agency in TARS
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void archiveAgencyTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String did = null;
        String xIBMClientSecret = null;
        api.archiveAgency(xIBMClientId, authorization, did, xIBMClientSecret);
        // TODO: test validations
    }

    /**
     * Close an agency in TARS
     *
     * Close an agency in TARS
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void closeAgencyTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String did = null;
        String xIBMClientSecret = null;
        api.closeAgency(xIBMClientId, authorization, did, xIBMClientSecret);
        // TODO: test validations
    }

    /**
     * Unarchive an agency in TARS
     *
     * Unarchive an agency in TARS
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unarchiveAgencyTest() throws ApiException {
        String xIBMClientId = null;
        String authorization = null;
        String did = null;
        String xIBMClientSecret = null;
        api.unarchiveAgency(xIBMClientId, authorization, did, xIBMClientSecret);
        // TODO: test validations
    }

}
