/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AgencyHeader;
import org.openapitools.client.model.AgencyTransaction;
import org.openapitools.client.model.MultiLang;
import org.openapitools.client.model.TradeLicense;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AgencyWithTransactions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-07T11:28:29.734525700+05:30[Asia/Calcutta]")
public class AgencyWithTransactions {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_DID = "did";
  @SerializedName(SERIALIZED_NAME_DID)
  private String did;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private String source;

  public static final String SERIALIZED_NAME_SOURCE_KEY = "sourceKey";
  @SerializedName(SERIALIZED_NAME_SOURCE_KEY)
  private String sourceKey;

  public static final String SERIALIZED_NAME_VERSION_HASH = "versionHash";
  @SerializedName(SERIALIZED_NAME_VERSION_HASH)
  private String versionHash;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private MultiLang name;

  public static final String SERIALIZED_NAME_CHAIN_NAME = "chainName";
  @SerializedName(SERIALIZED_NAME_CHAIN_NAME)
  private MultiLang chainName;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private AgencyHeader parent;

  public static final String SERIALIZED_NAME_TRAFFIC_FILE_NUMBER = "trafficFileNumber";
  @SerializedName(SERIALIZED_NAME_TRAFFIC_FILE_NUMBER)
  private String trafficFileNumber;

  public static final String SERIALIZED_NAME_TRADE_LICENSE = "tradeLicense";
  @SerializedName(SERIALIZED_NAME_TRADE_LICENSE)
  private TradeLicense tradeLicense;

  /**
   * Category of the Agency
   */
  @JsonAdapter(CategoryEnum.Adapter.class)
  public enum CategoryEnum {
    A("A"),
    
    B("B"),
    
    C("C"),
    
    D("D");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CategoryEnum fromValue(String value) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CategoryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CategoryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CategoryEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CategoryEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private CategoryEnum category;

  public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  private String imageUrl;

  /**
   * Status of the Agency
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    INACTIVE("INACTIVE"),
    
    ARCHIVED("ARCHIVED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "isActive";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive;

  public static final String SERIALIZED_NAME_IS_ARCHIVED = "isArchived";
  @SerializedName(SERIALIZED_NAME_IS_ARCHIVED)
  private Boolean isArchived;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_UPDATED_BY = "updatedBy";
  @SerializedName(SERIALIZED_NAME_UPDATED_BY)
  private String updatedBy;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_TRANSACTIONS = "transactions";
  @SerializedName(SERIALIZED_NAME_TRANSACTIONS)
  private List<AgencyTransaction> transactions;

  public AgencyWithTransactions() {
  }

  
  public AgencyWithTransactions(
     Long id, 
     String did, 
     String source, 
     String sourceKey, 
     String versionHash
  ) {
    this();
    this.id = id;
    this.did = did;
    this.source = source;
    this.sourceKey = sourceKey;
    this.versionHash = versionHash;
  }

   /**
   * Unique Identifier for the Agency. Autogenerated, not supplied by the consumer.
   * @return id
  **/
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }




   /**
   * Decentralized Identifier for the Agency
   * @return did
  **/
  @javax.annotation.Nullable
  public String getDid() {
    return did;
  }




   /**
   * Source for the Decentralized ID
   * @return source
  **/
  @javax.annotation.Nullable
  public String getSource() {
    return source;
  }




   /**
   * Natural Key from the Source
   * @return sourceKey
  **/
  @javax.annotation.Nullable
  public String getSourceKey() {
    return sourceKey;
  }




   /**
   * Hash of all trackable attributes
   * @return versionHash
  **/
  @javax.annotation.Nullable
  public String getVersionHash() {
    return versionHash;
  }




  public AgencyWithTransactions name(MultiLang name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public MultiLang getName() {
    return name;
  }


  public void setName(MultiLang name) {
    this.name = name;
  }


  public AgencyWithTransactions chainName(MultiLang chainName) {
    
    this.chainName = chainName;
    return this;
  }

   /**
   * Get chainName
   * @return chainName
  **/
  @javax.annotation.Nullable
  public MultiLang getChainName() {
    return chainName;
  }


  public void setChainName(MultiLang chainName) {
    this.chainName = chainName;
  }


  public AgencyWithTransactions parent(AgencyHeader parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  public AgencyHeader getParent() {
    return parent;
  }


  public void setParent(AgencyHeader parent) {
    this.parent = parent;
  }


  public AgencyWithTransactions trafficFileNumber(String trafficFileNumber) {
    
    this.trafficFileNumber = trafficFileNumber;
    return this;
  }

   /**
   * Traffic File Number of the Agency issued by RTA
   * @return trafficFileNumber
  **/
  @javax.annotation.Nullable
  public String getTrafficFileNumber() {
    return trafficFileNumber;
  }


  public void setTrafficFileNumber(String trafficFileNumber) {
    this.trafficFileNumber = trafficFileNumber;
  }


  public AgencyWithTransactions tradeLicense(TradeLicense tradeLicense) {
    
    this.tradeLicense = tradeLicense;
    return this;
  }

   /**
   * Get tradeLicense
   * @return tradeLicense
  **/
  @javax.annotation.Nullable
  public TradeLicense getTradeLicense() {
    return tradeLicense;
  }


  public void setTradeLicense(TradeLicense tradeLicense) {
    this.tradeLicense = tradeLicense;
  }


  public AgencyWithTransactions category(CategoryEnum category) {
    
    this.category = category;
    return this;
  }

   /**
   * Category of the Agency
   * @return category
  **/
  @javax.annotation.Nullable
  public CategoryEnum getCategory() {
    return category;
  }


  public void setCategory(CategoryEnum category) {
    this.category = category;
  }


  public AgencyWithTransactions imageUrl(String imageUrl) {
    
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Image URL
   * @return imageUrl
  **/
  @javax.annotation.Nullable
  public String getImageUrl() {
    return imageUrl;
  }


  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }


  public AgencyWithTransactions status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of the Agency
   * @return status
  **/
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public AgencyWithTransactions isActive(Boolean isActive) {
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Check with Agency is Active
   * @return isActive
  **/
  @javax.annotation.Nullable
  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  public AgencyWithTransactions isArchived(Boolean isArchived) {
    
    this.isArchived = isArchived;
    return this;
  }

   /**
   * Check with Agency is Archived
   * @return isArchived
  **/
  @javax.annotation.Nullable
  public Boolean getIsArchived() {
    return isArchived;
  }


  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }


  public AgencyWithTransactions createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Audit Field - Created By
   * @return createdBy
  **/
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public AgencyWithTransactions updatedBy(String updatedBy) {
    
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Audit Field - Updated By
   * @return updatedBy
  **/
  @javax.annotation.Nullable
  public String getUpdatedBy() {
    return updatedBy;
  }


  public void setUpdatedBy(String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public AgencyWithTransactions createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Audit Field - Created Timestamp
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AgencyWithTransactions updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Audit Field - Updated Timestamp
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public AgencyWithTransactions transactions(List<AgencyTransaction> transactions) {
    
    this.transactions = transactions;
    return this;
  }

  public AgencyWithTransactions addTransactionsItem(AgencyTransaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Permit issued by RTA
   * @return transactions
  **/
  @javax.annotation.Nullable
  public List<AgencyTransaction> getTransactions() {
    return transactions;
  }


  public void setTransactions(List<AgencyTransaction> transactions) {
    this.transactions = transactions;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgencyWithTransactions agencyWithTransactions = (AgencyWithTransactions) o;
    return Objects.equals(this.id, agencyWithTransactions.id) &&
        Objects.equals(this.did, agencyWithTransactions.did) &&
        Objects.equals(this.source, agencyWithTransactions.source) &&
        Objects.equals(this.sourceKey, agencyWithTransactions.sourceKey) &&
        Objects.equals(this.versionHash, agencyWithTransactions.versionHash) &&
        Objects.equals(this.name, agencyWithTransactions.name) &&
        Objects.equals(this.chainName, agencyWithTransactions.chainName) &&
        Objects.equals(this.parent, agencyWithTransactions.parent) &&
        Objects.equals(this.trafficFileNumber, agencyWithTransactions.trafficFileNumber) &&
        Objects.equals(this.tradeLicense, agencyWithTransactions.tradeLicense) &&
        Objects.equals(this.category, agencyWithTransactions.category) &&
        Objects.equals(this.imageUrl, agencyWithTransactions.imageUrl) &&
        Objects.equals(this.status, agencyWithTransactions.status) &&
        Objects.equals(this.isActive, agencyWithTransactions.isActive) &&
        Objects.equals(this.isArchived, agencyWithTransactions.isArchived) &&
        Objects.equals(this.createdBy, agencyWithTransactions.createdBy) &&
        Objects.equals(this.updatedBy, agencyWithTransactions.updatedBy) &&
        Objects.equals(this.createdAt, agencyWithTransactions.createdAt) &&
        Objects.equals(this.updatedAt, agencyWithTransactions.updatedAt) &&
        Objects.equals(this.transactions, agencyWithTransactions.transactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, did, source, sourceKey, versionHash, name, chainName, parent, trafficFileNumber, tradeLicense, category, imageUrl, status, isActive, isArchived, createdBy, updatedBy, createdAt, updatedAt, transactions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgencyWithTransactions {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    did: ").append(toIndentedString(did)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    sourceKey: ").append(toIndentedString(sourceKey)).append("\n");
    sb.append("    versionHash: ").append(toIndentedString(versionHash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    chainName: ").append(toIndentedString(chainName)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    trafficFileNumber: ").append(toIndentedString(trafficFileNumber)).append("\n");
    sb.append("    tradeLicense: ").append(toIndentedString(tradeLicense)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isArchived: ").append(toIndentedString(isArchived)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("did");
    openapiFields.add("source");
    openapiFields.add("sourceKey");
    openapiFields.add("versionHash");
    openapiFields.add("name");
    openapiFields.add("chainName");
    openapiFields.add("parent");
    openapiFields.add("trafficFileNumber");
    openapiFields.add("tradeLicense");
    openapiFields.add("category");
    openapiFields.add("imageUrl");
    openapiFields.add("status");
    openapiFields.add("isActive");
    openapiFields.add("isArchived");
    openapiFields.add("createdBy");
    openapiFields.add("updatedBy");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("transactions");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AgencyWithTransactions
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AgencyWithTransactions.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AgencyWithTransactions is not found in the empty JSON string", AgencyWithTransactions.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AgencyWithTransactions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AgencyWithTransactions` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("did") != null && !jsonObj.get("did").isJsonNull()) && !jsonObj.get("did").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `did` to be a primitive type in the JSON string but got `%s`", jsonObj.get("did").toString()));
      }
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      if ((jsonObj.get("sourceKey") != null && !jsonObj.get("sourceKey").isJsonNull()) && !jsonObj.get("sourceKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sourceKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sourceKey").toString()));
      }
      if ((jsonObj.get("versionHash") != null && !jsonObj.get("versionHash").isJsonNull()) && !jsonObj.get("versionHash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `versionHash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("versionHash").toString()));
      }
      // validate the optional field `name`
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) {
        MultiLang.validateJsonObject(jsonObj.getAsJsonObject("name"));
      }
      // validate the optional field `chainName`
      if (jsonObj.get("chainName") != null && !jsonObj.get("chainName").isJsonNull()) {
        MultiLang.validateJsonObject(jsonObj.getAsJsonObject("chainName"));
      }
      // validate the optional field `parent`
      if (jsonObj.get("parent") != null && !jsonObj.get("parent").isJsonNull()) {
        AgencyHeader.validateJsonObject(jsonObj.getAsJsonObject("parent"));
      }
      if ((jsonObj.get("trafficFileNumber") != null && !jsonObj.get("trafficFileNumber").isJsonNull()) && !jsonObj.get("trafficFileNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `trafficFileNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trafficFileNumber").toString()));
      }
      // validate the optional field `tradeLicense`
      if (jsonObj.get("tradeLicense") != null && !jsonObj.get("tradeLicense").isJsonNull()) {
        TradeLicense.validateJsonObject(jsonObj.getAsJsonObject("tradeLicense"));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      if ((jsonObj.get("imageUrl") != null && !jsonObj.get("imageUrl").isJsonNull()) && !jsonObj.get("imageUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageUrl").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("createdBy") != null && !jsonObj.get("createdBy").isJsonNull()) && !jsonObj.get("createdBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdBy").toString()));
      }
      if ((jsonObj.get("updatedBy") != null && !jsonObj.get("updatedBy").isJsonNull()) && !jsonObj.get("updatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedBy").toString()));
      }
      if (jsonObj.get("transactions") != null && !jsonObj.get("transactions").isJsonNull()) {
        JsonArray jsonArraytransactions = jsonObj.getAsJsonArray("transactions");
        if (jsonArraytransactions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("transactions").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `transactions` to be an array in the JSON string but got `%s`", jsonObj.get("transactions").toString()));
          }

          // validate the optional field `transactions` (array)
          for (int i = 0; i < jsonArraytransactions.size(); i++) {
            AgencyTransaction.validateJsonObject(jsonArraytransactions.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AgencyWithTransactions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AgencyWithTransactions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AgencyWithTransactions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AgencyWithTransactions.class));

       return (TypeAdapter<T>) new TypeAdapter<AgencyWithTransactions>() {
           @Override
           public void write(JsonWriter out, AgencyWithTransactions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AgencyWithTransactions read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AgencyWithTransactions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AgencyWithTransactions
  * @throws IOException if the JSON string is invalid with respect to AgencyWithTransactions
  */
  public static AgencyWithTransactions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AgencyWithTransactions.class);
  }

 /**
  * Convert an instance of AgencyWithTransactions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

