/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * LanguageMapper
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-07T11:28:29.734525700+05:30[Asia/Calcutta]")
public class LanguageMapper {
  public static final String SERIALIZED_NAME_EN = "en";
  @SerializedName(SERIALIZED_NAME_EN)
  private String en;

  public static final String SERIALIZED_NAME_AR = "ar";
  @SerializedName(SERIALIZED_NAME_AR)
  private String ar;

  public LanguageMapper() {
  }

  public LanguageMapper en(String en) {
    
    this.en = en;
    return this;
  }

   /**
   * Name in English
   * @return en
  **/
  @javax.annotation.Nullable
  public String getEn() {
    return en;
  }


  public void setEn(String en) {
    this.en = en;
  }


  public LanguageMapper ar(String ar) {
    
    this.ar = ar;
    return this;
  }

   /**
   * Name in Arabic
   * @return ar
  **/
  @javax.annotation.Nullable
  public String getAr() {
    return ar;
  }


  public void setAr(String ar) {
    this.ar = ar;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageMapper languageMapper = (LanguageMapper) o;
    return Objects.equals(this.en, languageMapper.en) &&
        Objects.equals(this.ar, languageMapper.ar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(en, ar);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageMapper {\n");
    sb.append("    en: ").append(toIndentedString(en)).append("\n");
    sb.append("    ar: ").append(toIndentedString(ar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("en");
    openapiFields.add("ar");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LanguageMapper
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LanguageMapper.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LanguageMapper is not found in the empty JSON string", LanguageMapper.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LanguageMapper.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LanguageMapper` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("en") != null && !jsonObj.get("en").isJsonNull()) && !jsonObj.get("en").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `en` to be a primitive type in the JSON string but got `%s`", jsonObj.get("en").toString()));
      }
      if ((jsonObj.get("ar") != null && !jsonObj.get("ar").isJsonNull()) && !jsonObj.get("ar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ar").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LanguageMapper.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LanguageMapper' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LanguageMapper> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LanguageMapper.class));

       return (TypeAdapter<T>) new TypeAdapter<LanguageMapper>() {
           @Override
           public void write(JsonWriter out, LanguageMapper value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LanguageMapper read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LanguageMapper given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LanguageMapper
  * @throws IOException if the JSON string is invalid with respect to LanguageMapper
  */
  public static LanguageMapper fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LanguageMapper.class);
  }

 /**
  * Convert an instance of LanguageMapper to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

