/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.CodeName;
import org.openapitools.client.model.Location;
import org.openapitools.client.model.MultiLang;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Address
 */
public class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    public void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'makani'
     */
    @Test
    public void makaniTest() {
        // TODO: test makani
    }

    /**
     * Test the property 'poBox'
     */
    @Test
    public void poBoxTest() {
        // TODO: test poBox
    }

    /**
     * Test the property 'area'
     */
    @Test
    public void areaTest() {
        // TODO: test area
    }

    /**
     * Test the property 'subArea'
     */
    @Test
    public void subAreaTest() {
        // TODO: test subArea
    }

    /**
     * Test the property 'community'
     */
    @Test
    public void communityTest() {
        // TODO: test community
    }

    /**
     * Test the property 'unit'
     */
    @Test
    public void unitTest() {
        // TODO: test unit
    }

    /**
     * Test the property 'building'
     */
    @Test
    public void buildingTest() {
        // TODO: test building
    }

    /**
     * Test the property 'street'
     */
    @Test
    public void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'emirate'
     */
    @Test
    public void emirateTest() {
        // TODO: test emirate
    }

    /**
     * Test the property 'geoLocation'
     */
    @Test
    public void geoLocationTest() {
        // TODO: test geoLocation
    }

    /**
     * Test the property 'preferred'
     */
    @Test
    public void preferredTest() {
        // TODO: test preferred
    }

}
