/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.LanguageMapper;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyPartner
 */
public class AgencyPartnerTest {
    private final AgencyPartner model = new AgencyPartner();

    /**
     * Model tests for AgencyPartner
     */
    @Test
    public void testAgencyPartner() {
        // TODO: test AgencyPartner
    }

    /**
     * Test the property 'partnerNo'
     */
    @Test
    public void partnerNoTest() {
        // TODO: test partnerNo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'emiratesId'
     */
    @Test
    public void emiratesIdTest() {
        // TODO: test emiratesId
    }

    /**
     * Test the property 'passportNumber'
     */
    @Test
    public void passportNumberTest() {
        // TODO: test passportNumber
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'personCategory'
     */
    @Test
    public void personCategoryTest() {
        // TODO: test personCategory
    }

    /**
     * Test the property 'legalType'
     */
    @Test
    public void legalTypeTest() {
        // TODO: test legalType
    }

    /**
     * Test the property 'percentOwnership'
     */
    @Test
    public void percentOwnershipTest() {
        // TODO: test percentOwnership
    }

    /**
     * Test the property 'residenceNumber'
     */
    @Test
    public void residenceNumberTest() {
        // TODO: test residenceNumber
    }

    /**
     * Test the property 'effectiveStartDate'
     */
    @Test
    public void effectiveStartDateTest() {
        // TODO: test effectiveStartDate
    }

    /**
     * Test the property 'effectiveEndDate'
     */
    @Test
    public void effectiveEndDateTest() {
        // TODO: test effectiveEndDate
    }

}
