/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LanguageMapper;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyPermit
 */
public class AgencyPermitTest {
    private final AgencyPermit model = new AgencyPermit();

    /**
     * Model tests for AgencyPermit
     */
    @Test
    public void testAgencyPermit() {
        // TODO: test AgencyPermit
    }

    /**
     * Test the property 'permitNo'
     */
    @Test
    public void permitNoTest() {
        // TODO: test permitNo
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'issuedDate'
     */
    @Test
    public void issuedDateTest() {
        // TODO: test issuedDate
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'authorityName'
     */
    @Test
    public void authorityNameTest() {
        // TODO: test authorityName
    }

    /**
     * Test the property 'owners'
     */
    @Test
    public void ownersTest() {
        // TODO: test owners
    }

    /**
     * Test the property 'managers'
     */
    @Test
    public void managersTest() {
        // TODO: test managers
    }

}
