/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.MultiLang;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyCommerceRegistry
 */
public class AgencyCommerceRegistryTest {
    private final AgencyCommerceRegistry model = new AgencyCommerceRegistry();

    /**
     * Model tests for AgencyCommerceRegistry
     */
    @Test
    public void testAgencyCommerceRegistry() {
        // TODO: test AgencyCommerceRegistry
    }

    /**
     * Test the property 'registerSerialNumber'
     */
    @Test
    public void registerSerialNumberTest() {
        // TODO: test registerSerialNumber
    }

    /**
     * Test the property 'ucrNumber'
     */
    @Test
    public void ucrNumberTest() {
        // TODO: test ucrNumber
    }

    /**
     * Test the property 'commerceNumber'
     */
    @Test
    public void commerceNumberTest() {
        // TODO: test commerceNumber
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'mainLicenseNumber'
     */
    @Test
    public void mainLicenseNumberTest() {
        // TODO: test mainLicenseNumber
    }

    /**
     * Test the property 'commerceRegisterType'
     */
    @Test
    public void commerceRegisterTypeTest() {
        // TODO: test commerceRegisterType
    }

    /**
     * Test the property 'legalType'
     */
    @Test
    public void legalTypeTest() {
        // TODO: test legalType
    }

    /**
     * Test the property 'nationality'
     */
    @Test
    public void nationalityTest() {
        // TODO: test nationality
    }

    /**
     * Test the property 'issueDate'
     */
    @Test
    public void issueDateTest() {
        // TODO: test issueDate
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'cancelDate'
     */
    @Test
    public void cancelDateTest() {
        // TODO: test cancelDate
    }

    /**
     * Test the property 'paidUpCapital'
     */
    @Test
    public void paidUpCapitalTest() {
        // TODO: test paidUpCapital
    }

    /**
     * Test the property 'nominalCapital'
     */
    @Test
    public void nominalCapitalTest() {
        // TODO: test nominalCapital
    }

}
