/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AgencyActivity;
import org.openapitools.client.model.AgencyCommerceRegistry;
import org.openapitools.client.model.AgencyOrganization;
import org.openapitools.client.model.AgencyPartner;
import org.openapitools.client.model.AgencyPermit;
import org.openapitools.client.model.Attachment;
import org.openapitools.client.model.Contact;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyDetails
 */
public class AgencyDetailsTest {
    private final AgencyDetails model = new AgencyDetails();

    /**
     * Model tests for AgencyDetails
     */
    @Test
    public void testAgencyDetails() {
        // TODO: test AgencyDetails
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'permit'
     */
    @Test
    public void permitTest() {
        // TODO: test permit
    }

    /**
     * Test the property 'partners'
     */
    @Test
    public void partnersTest() {
        // TODO: test partners
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'activity'
     */
    @Test
    public void activityTest() {
        // TODO: test activity
    }

    /**
     * Test the property 'commerceRegistry'
     */
    @Test
    public void commerceRegistryTest() {
        // TODO: test commerceRegistry
    }

}
