/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.MultiLang;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyHeader
 */
public class AgencyHeaderTest {
    private final AgencyHeader model = new AgencyHeader();

    /**
     * Model tests for AgencyHeader
     */
    @Test
    public void testAgencyHeader() {
        // TODO: test AgencyHeader
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'did'
     */
    @Test
    public void didTest() {
        // TODO: test did
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'sourceKey'
     */
    @Test
    public void sourceKeyTest() {
        // TODO: test sourceKey
    }

    /**
     * Test the property 'versionHash'
     */
    @Test
    public void versionHashTest() {
        // TODO: test versionHash
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'chainName'
     */
    @Test
    public void chainNameTest() {
        // TODO: test chainName
    }

    /**
     * Test the property 'tradeLicenseNumber'
     */
    @Test
    public void tradeLicenseNumberTest() {
        // TODO: test tradeLicenseNumber
    }

}
