/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.MultiLang;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyActivity
 */
public class AgencyActivityTest {
    private final AgencyActivity model = new AgencyActivity();

    /**
     * Model tests for AgencyActivity
     */
    @Test
    public void testAgencyActivity() {
        // TODO: test AgencyActivity
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'effectiveStartDate'
     */
    @Test
    public void effectiveStartDateTest() {
        // TODO: test effectiveStartDate
    }

    /**
     * Test the property 'effectiveEndDate'
     */
    @Test
    public void effectiveEndDateTest() {
        // TODO: test effectiveEndDate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
