/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyTransactionDetails
 */
public class AgencyTransactionDetailsTest {
    private final AgencyTransactionDetails model = new AgencyTransactionDetails();

    /**
     * Model tests for AgencyTransactionDetails
     */
    @Test
    public void testAgencyTransactionDetails() {
        // TODO: test AgencyTransactionDetails
    }

    /**
     * Test the property 'meetingPlace'
     */
    @Test
    public void meetingPlaceTest() {
        // TODO: test meetingPlace
    }

}
