/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.LanguageMapper;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AgencyOrganization
 */
public class AgencyOrganizationTest {
    private final AgencyOrganization model = new AgencyOrganization();

    /**
     * Model tests for AgencyOrganization
     */
    @Test
    public void testAgencyOrganization() {
        // TODO: test AgencyOrganization
    }

    /**
     * Test the property 'licenseType'
     */
    @Test
    public void licenseTypeTest() {
        // TODO: test licenseType
    }

    /**
     * Test the property 'legalType'
     */
    @Test
    public void legalTypeTest() {
        // TODO: test legalType
    }

    /**
     * Test the property 'classDescription'
     */
    @Test
    public void classDescriptionTest() {
        // TODO: test classDescription
    }

    /**
     * Test the property 'representedBy'
     */
    @Test
    public void representedByTest() {
        // TODO: test representedBy
    }

    /**
     * Test the property 'issuedDate'
     */
    @Test
    public void issuedDateTest() {
        // TODO: test issuedDate
    }

    /**
     * Test the property 'expriyDate'
     */
    @Test
    public void expriyDateTest() {
        // TODO: test expriyDate
    }

}
