/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MultiLang
 */
public class MultiLangTest {
    private final MultiLang model = new MultiLang();

    /**
     * Model tests for MultiLang
     */
    @Test
    public void testMultiLang() {
        // TODO: test MultiLang
    }

    /**
     * Test the property 'en'
     */
    @Test
    public void enTest() {
        // TODO: test en
    }

    /**
     * Test the property 'ar'
     */
    @Test
    public void arTest() {
        // TODO: test ar
    }

}
