/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SimCard
 */
public class SimCardTest {
    private final SimCard model = new SimCard();

    /**
     * Model tests for SimCard
     */
    @Test
    public void testSimCard() {
        // TODO: test SimCard
    }

    /**
     * Test the property 'trafficFileNo'
     */
    @Test
    public void trafficFileNoTest() {
        // TODO: test trafficFileNo
    }

    /**
     * Test the property 'tradeLicenseNo'
     */
    @Test
    public void tradeLicenseNoTest() {
        // TODO: test tradeLicenseNo
    }

    /**
     * Test the property 'simCardReceived'
     */
    @Test
    public void simCardReceivedTest() {
        // TODO: test simCardReceived
    }

}
