/*
 * Agency
 * Manage Agency Information 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TradeLicense
 */
public class TradeLicenseTest {
    private final TradeLicense model = new TradeLicense();

    /**
     * Model tests for TradeLicense
     */
    @Test
    public void testTradeLicense() {
        // TODO: test TradeLicense
    }

    /**
     * Test the property 'licenseNo'
     */
    @Test
    public void licenseNoTest() {
        // TODO: test licenseNo
    }

    /**
     * Test the property 'issuedDate'
     */
    @Test
    public void issuedDateTest() {
        // TODO: test issuedDate
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

}
